
-- 手动插入的token_expand数据
INSERT INTO token_expand (address, icon, web_site, details, is_show_in_aton, is_show_in_scan, is_can_transfer,
                          create_id, create_name, create_time, update_id, update_name, update_time, is_show_in_aton_admin, is_show_in_scan_admin)
VALUES ('lat1w9ys9726hyhqk9yskffgly08xanpzdgqvp2sz6', null, 'https://www.qpassport.io/', 'QPassport, a next-generation decentralized identifier, aims to build a decentralized, transparent, secure, and open ID system, credit system, and data storage and management system. QPassport is of the user, by the user, and for the user.',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat13m53valp38lsaq6p234754gau54sdjw0fqymys', null, 'https://app.qpassport.io/#/event/MetaFireworks', '"MetaFireworks" is a series of NFTs jointly launched by QPassport and PlatON as a gift for metaverse players, wishing it could dispel the gloom of the epidemic and bring you joy, happiness and love.',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat1mqs7hxfgthqk533pshxwtntaxnqqgdhxn009xa', null, 'https://www.platon.network/', 'PlatON Limited Badge, for PlatON Genesis, Friends, Contributors, Communities. "We shall always keep to the upper road and practice justice with prudence in every way."',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat16axyya4lygaj9hskapsqdkhrnp6gke6nnl3dud', null, 'https://StoneAeon.io/', 'Stone Aeon NFT 8128 unique SANFTs with over 300 hand-painted features. All SANFTS are high definition art collectibles and are symbols of VIP. Holders will receive management rights to StoneAeon and continue to receive the proceeds of the project.',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat14exhe3xtrxr6januwkljnl77xqc0nzj7c4hnck', null, '', 'An original NFT created by OKEx',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat12v6d2mguvnh4wm2d65k9sf5t2t8z9urer55u08', null, 'https://www.platon.network/', 'PlatON MainNetwork launch is decided by community voting, each Ticket is a ballot, and sending a Ticket to the voting receiving address means supporting the current PlatON network (chainID:100) to become the PlatON MainNetwork .',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat18q52swex23j8nf6m8lpsu9h7g0a6w7ecfxmfea', null, 'https://app.qpassport.io/#/event/MetaFireworks', '"Metafireworks of Your Dreams" is a series of NFTs jointly launched by QPassport and OneCash as a gift for metaverse players. No matter how far apart you are, you can still feel the good wishes.',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat1dgkjvt2kwdwm5xwawp5zkw0kh6dfx8vcc2fkru', null, 'https://cbridge.celer.network/', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat1juqr5zqdxg82q9d7mw3smuj7vhwry9j06swauq', null, 'https://bridge.platon.network/bridge', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat1s8k2crttup2s5q8lqe9yl8wjgqzctl5u0mmdpx', null, 'https://cbridge.celer.network/', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat1qfqx64ssd8976fl0363q4l2pw7dfpc4llufrj5', null, '', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat19n7chtz507957nlge70du6z96rrfe09p4rkezk', null, 'https://bridge.platon.network/bridge', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat1f0mknvz7svhumjg98llmc7x23zdvkhs70v27yk', null, 'https://cbridge.celer.network/', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT),
       ('lat10unn2t2ls0dc0fdruq85kp7vyyud3mjj7gawlp', null, 'https://cbridge.celer.network/', '',
        DEFAULT, 1, DEFAULT, 0, '', DEFAULT, 0, '', DEFAULT, DEFAULT, DEFAULT);
